### ISSUE TITLE
Support positional arguments

### ISSUE THREAD

**Issue by unsolaci** [arkjedrz/zxc#22]
It seems like currently only named parameters for commands are supported, e.g. `-n John` or `--name John`.

It would be a nice addition to also support positional arguments when specified, like so:
```
greet:
  command: echo "Hello {{ name }}!"
  description: Greets specified person.
  arguments:
    name:
      description: |-
        Name to greet.
      default: User
      long: name
      short: n
      position: 1
```

That way, the user could omit the `-n`/`--name` and simply supply the value at the specified position:
```
zxc greet John
```
